steps:
  - id: Build
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-images/$_SERVICE_NAME:$COMMIT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-images/$_SERVICE_NAME:latest'
      - '.'

  - id: Push
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-images/$_SERVICE_NAME'

  - id: Deploy
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update'
      - '$_SERVICE_NAME'
      - '--platform=managed'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-images/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region=$_REGION'
      - '--quiet'

substitutions:
  _SERVICE_NAME: default
  _REGION: us-central1

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-images/$_SERVICE_NAME:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-images/$_SERVICE_NAME:latest'

options:
  logging: CLOUD_LOGGING_ONLY
